name: studrow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.7.0
  swipe_cards: ^2.0.0+1
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3
  auto_route: ^8.0.3
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
  sqflite: ^2.2.8
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
