name: Android-apk-build

on:
  workflow_dispatch:   # запуск вручну через GitHub → Actions → Run workflow

jobs:
  build-android:
    name: 🤖 Android Build
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонування репозиторію
      - uses: actions/checkout@v4

      # 2️⃣ Встановлення Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3️⃣ Встановлення залежностей
      - name: Get dependencies
        run: flutter pub get

      # 4️⃣ Збірка APK (debug або release)
      - name: Build APK
        run: flutter build apk --release

      # 🧩 Якщо потрібно .aab для Play Store:
      # - name: Build App Bundle
      #   run: flutter build appbundle --release

      # 5️⃣ Завантаження APK у релізи GitHub
      - name: Upload APK to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          tag: v1.0
          overwrite: true
          body: "Android release build"